// src/pages/VallarchiPlan.tsx

import React, { useState } from 'react';
import { Card, Select, Checkbox, Button, Space, List, Typography, Row, Col } from 'antd';
import { useCurrentDate } from '../hooks/useCurrentDate';
import type { Product, Task, PlanDetails } from '../types';

const { Option } = Select;
const { Title, Text } = Typography;

const VallarchiPlan: React.FC = () => {
  const { getFormattedDateShort } = useCurrentDate();
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [planDetails, setPlanDetails] = useState<PlanDetails | null>(null);

  const products: Product[] = [
    { id: '1', name: 'Product A' },
    { id: '2', name: 'Product B' },
    { id: '3', name: 'Product C' }
  ];

  const [tasks, setTasks] = useState<Task[]>([
    { id: '1', title: 'Multicity development', completed: true },
    { id: '2', title: 'Flight flow responsive development', completed: false },
    { id: '3', title: 'List page revamp', completed: true },
    { id: '4', title: 'API Migration', completed: false }
  ]);

  const onProductChange = (productId: string) => {
    const product = products.find(p => p.id === productId) || null;
    setSelectedProduct(product);
    loadProductDetails(product);
  };

  const loadProductDetails = (product: Product | null) => {
    if (product) {
      setPlanDetails({
        tasks: [
          'Multicity development 80% completed',
          'List page revamp integrates'
        ]
      });
    } else {
      setPlanDetails(null);
    }
  };

  const onTaskChange = (taskId: string) => {
    setTasks(tasks.map(task => 
      task.id === taskId ? { ...task, completed: !task.completed } : task
    ));
  };

  const onSubmitAndView = () => {
    console.log('Submit and view clicked');
    // Handle submit and view action
  };

  const onSendToManager = () => {
    console.log('Send to manager clicked');
    // Handle send to manager action
  };

  return (
    <div style={{ padding: '24px' }}>
      <Card title="Vallarchi Plan" style={{ marginBottom: '24px' }}>
        <Row gutter={16}>
          <Col xs={24} sm={12}>
            <Title level={4}>Date: {getFormattedDateShort()}</Title>
          </Col>
          <Col xs={24} sm={12}>
            <Space direction="vertical" style={{ width: '100%' }}>
              <Text strong>Select Product:</Text>
              <Select
                style={{ width: '100%' }}
                placeholder="Choose a product"
                onChange={onProductChange}
                value={selectedProduct?.id}
              >
                {products.map(product => (
                  <Option key={product.id} value={product.id}>
                    {product.name}
                  </Option>
                ))}
              </Select>
            </Space>
          </Col>
        </Row>
      </Card>

      {planDetails && (
        <Card title="Product Details" style={{ marginBottom: '24px' }}>
          <List
            dataSource={planDetails.tasks}
            renderItem={(task) => (
              <List.Item>
                <Text>{task}</Text>
              </List.Item>
            )}
          />
        </Card>
      )}

      <Card title="Tasks" style={{ marginBottom: '24px' }}>
        <Space direction="vertical" style={{ width: '100%' }}>
          {tasks.map(task => (
            <Checkbox
              key={task.id}
              checked={task.completed}
              onChange={() => onTaskChange(task.id)}
            >
              {task.title}
            </Checkbox>
          ))}
        </Space>
      </Card>

      <Card>
        <Space>
          <Button type="primary" onClick={onSubmitAndView}>
            Submit and View
          </Button>
          <Button onClick={onSendToManager}>
            Send to Manager
          </Button>
        </Space>
      </Card>
    </div>
  );
};

export default VallarchiPlan;

// src/app/vallarchi/vallarchi-plan/vallarchi-plan.component.ts
import { Component, OnInit } from '@angular/core';
interface Product {
  id: string;
  name: string;
}

interface Task {
  id: string;
  title: string;
  completed: boolean;
  progress?: number;
}

interface PlanDetails {
  tasks: string[];
}
@Component({
  selector: 'app-vallarchi-plan',
  templateUrl: './vallarchi-plan.component.html',
  styleUrls: ['./vallarchi-plan.component.scss']
})
export class VallarchiPlanComponent implements OnInit {

 currentDate = new Date();
  selectedProduct: Product | null = null;
  planDetails: PlanDetails | null = null;

  products: Product[] = [
    { id: '1', name: 'Product A' },
    { id: '2', name: 'Product B' },
    { id: '3', name: 'Product C' }
  ];

  tasks: Task[] = [
    { id: '1', title: 'Multicity development', completed: true },
    { id: '2', title: 'Flight flow responsive development', completed: false },
    { id: '3', title: 'List page revamp', completed: true },
    { id: '4', title: 'API Migration', completed: false }
  ];

  constructor() { }

  ngOnInit(): void {
    // Initialize with empty product details
    this.planDetails = null;
  }

  onProductChange(product: Product): void {
    this.selectedProduct = product;
    this.loadProductDetails();
  }

  loadProductDetails(): void {
    if (this.selectedProduct) {
      // Simulate loading product details
      this.planDetails = {
        tasks: [
          'Multicity development 80% completed',
          'List page revamp integrates'
        ]
      };
    } else {
      this.planDetails = null;
    }
  }

  onTaskChange(task: Task): void {
    task.completed = !task.completed;
  }

  onSubmitAndView(): void {
    console.log('Submit and view clicked');
    // Handle submit and view action
  }

  onSendToManager(): void {
    console.log('Send to manager clicked');
    // Handle send to manager action
  }

  getFormattedDate(): string {
    const day = this.currentDate.getDate();
    const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const month = monthNames[this.currentDate.getMonth()];
    const year = this.currentDate.getFullYear();
    
    return `${day}, ${month} ${year}`;
  }
}


<div class="plan-management-container">
  <!-- Header Section -->
  <div class="header-section">
    <div class="date-info">
      <span class="date-number">{{ currentDate.getDate() }}</span>
      <span class="date-text">{{ getFormattedDate().split(',')[1] }}</span>
    </div>
    
    <div class="product-dropdown">
      <select 
        class="product-select" 
       
        [value]="selectedProduct?.id || ''">
        <option value="">Select product</option>
        <option *ngFor="let product of products" [value]="product.id">
          {{ product.name }}
        </option>
      </select>
    </div>
  </div>

  <!-- Main Content -->
  <div class="main-content">
    <!-- Plan Title -->
    <div class="plan-title">
      <h2>Vallarchi plan for (Feb) last month</h2>
      <button class="filter-btn" type="button">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"></polygon>
        </svg>
      </button>
    </div>

    <!-- Content Area -->
    <div class="content-area">
      <!-- Left Panel - Task List -->
      <div class="left-panel">
        <div class="task-selection">
          <select class="task-select">
            <option>Select vallarchi task</option>
          </select>
        </div>

        <div class="task-list">
          <div *ngFor="let task of tasks" class="task-item">
            <label class="task-label">
              <input 
                type="checkbox" 
                [checked]="task.completed"
                (change)="onTaskChange(task)"
                class="task-checkbox">
              <span class="task-text">{{ task.title }}</span>
            </label>
          </div>
        </div>

        <button class="submit-view-btn" (click)="onSubmitAndView()">
          Submit and view
        </button>
      </div>

      <!-- Right Panel - Product Details -->
      <div class="right-panel">
        <div class="product-details" *ngIf="planDetails; else emptyState">
          <div class="detail-item" *ngFor="let detail of planDetails.tasks; let i = index">
            <span class="detail-number">{{ i + 1 }}.</span>
            <span class="detail-text">{{ detail }}</span>
            <button class="edit-btn" type="button">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
                <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4Z"></path>
              </svg>
            </button>
          </div>
          
          <div class="manager-section">
            <button class="send-manager-btn" (click)="onSendToManager()">
              Send to manager
            </button>
          </div>
        </div>

        <ng-template #emptyState>
          <div class="empty-state">
            <p>Select a product to view details</p>
          </div>
        </ng-template>
      </div>
    </div>
  </div>
</div>
