// src/app/team-activity/team-activity.component.ts

import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, FormArray, Validators } from '@angular/forms';

interface TaskRow {
  id: number;
  mainTask: string;
  subTask: string;
  todayTask: string;
  resourceName: string;
  phaseAndSprint: string;
  status: string;
  taskStartDate: Date;
  taskEndDate: Date;
  comments: string;
}

@Component({
  selector: 'app-team-activity',
  templateUrl: './team-activity.component.html',
  styleUrls: ['./team-activity.component.scss']
})
export class TeamActivityComponent implements OnInit {
  teamActivityForm: FormGroup;
  currentDate = new Date();
  
  mainTaskOptions = [
    'Development',
    'Testing',
    'Design',
    'Documentation',
    'Planning'
  ];

  subTaskOptions = [
    'Frontend Development',
    'Backend Development',
    'API Integration',
    'Unit Testing',
    'Integration Testing',
    'UI Design',
    'UX Research'
  ];

  resourceOptions = [
    'John Doe',
    'Jane Smith',
    'Mike Johnson',
    'Sarah Wilson',
    'David Brown'
  ];

  phaseOptions = [
    'Phase 1 - Sprint 1',
    'Phase 1 - Sprint 2',
    'Phase 2 - Sprint 1',
    'Phase 2 - Sprint 2'
  ];

  statusOptions = [
    'Not Started',
    'In Progress',
    'Completed',
    'Blocked',
    'On Hold'
  ];
products= [
  "Product1",
  "Product2",
  "Product3"
]
  constructor(private fb: FormBuilder) {
    this.teamActivityForm = this.fb.group({
      date: [this.formatDate(this.currentDate), Validators.required],
      workingResources: ['', [Validators.required, Validators.min(1)]],
      selectedProduct: [''],
      tasks: this.fb.array([])
    });
  }

  ngOnInit(): void {
    this.addTaskRow();
    this.addTaskRow();
    this.addTaskRow();
  }

  get tasksFormArray(): FormArray {
    return this.teamActivityForm.get('tasks') as FormArray;
  }

  createTaskRow(): FormGroup {
    return this.fb.group({
      mainTask: ['', Validators.required],
      subTask: ['', Validators.required],
      todayTask: ['', Validators.required],
      resourceName: ['', Validators.required],
      phaseAndSprint: ['', Validators.required],
      status: ['', Validators.required],
      taskStartDate: [this.formatDate(this.currentDate), Validators.required],
      taskEndDate: [this.formatDate(this.addDays(this.currentDate, 7)), Validators.required],
      comments: ['']
    });
  }

  addTaskRow(): void {
    this.tasksFormArray.push(this.createTaskRow());
  }

  removeTaskRow(index: number): void {
    if (this.tasksFormArray.length > 1) {
      this.tasksFormArray.removeAt(index);
    }
  }

  onSubmit(): void {
    if (this.teamActivityForm.valid) {
      const formData = this.teamActivityForm.value;
      console.log('Team Activity Data:', formData);
      // Handle form submission here
      alert('Team activity submitted successfully!');
    } else {
      this.markFormGroupTouched();
    }
  }

  private markFormGroupTouched(): void {
    Object.keys(this.teamActivityForm.controls).forEach(key => {
      const control = this.teamActivityForm.get(key);
      control?.markAsTouched();
    });

    this.tasksFormArray.controls.forEach(taskGroup => {
      Object.keys(taskGroup.value).forEach(key => {
        const control = taskGroup.get(key);
        control?.markAsTouched();
      });
    });
  }

  private formatDate(date: Date): string {
    return date.toISOString().split('T')[0];
  }

  private addDays(date: Date, days: number): Date {
    const result = new Date(date);
    result.setDate(result.getDate() + days);
    return result;
  }

}


<div class="team-activity-container">
  <!-- Sidebar Navigation -->
   <app-header [productData]="products"></app-header>
  <div class="main-content">
   

    <!-- Team Activity Form -->
    <div class="content-area">
      <form [formGroup]="teamActivityForm" (ngSubmit)="onSubmit()">
        <div class="activity-header">
          <h3>Team activity</h3>
          
          <div class="form-row">
            <div class="form-group">
              <label for="date">Date:</label>
              <input 
                type="date" 
                id="date" 
                formControlName="date"
                class="form-control date-input">
            </div>
            
            <div class="form-group">
              <label for="workingResources">No of working resource:</label>
              <input 
                type="number" 
                id="workingResources" 
                formControlName="workingResources"
                class="form-control number-input"
                min="1">
            </div>
          </div>
        </div>

        <!-- Tasks Table -->
        <div class="table-container">
          <table class="tasks-table">
            <thead>
              <tr>
                <th>S.no</th>
                <th>Main task</th>
                <th>Sub task</th>
                <th>Today task</th>
                <th>Resource name</th>
                <th>Phase & Sprint</th>
                <th>Status</th>
                <th>Task start - end date range</th>
                <th>Comments</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody formArrayName="tasks">
              <tr *ngFor="let task of tasksFormArray.controls; let i = index" [formGroupName]="i">
                <td>{{ i + 1 }}</td>
                
                <td>
                  <select formControlName="mainTask" class="form-control">
                    <option value="">select main task</option>
                    <option *ngFor="let option of mainTaskOptions" [value]="option">
                      {{ option }}
                    </option>
                  </select>
                </td>
                
                <td>
                  <select formControlName="subTask" class="form-control">
                    <option value="">select sub task</option>
                    <option *ngFor="let option of subTaskOptions" [value]="option">
                      {{ option }}
                    </option>
                  </select>
                </td>
                
                <td>
                  <input 
                    type="text" 
                    formControlName="todayTask"
                    class="form-control"
                    placeholder="Enter today's task">
                </td>
                
                <td>
                  <select formControlName="resourceName" class="form-control">
                    <option value="">Select resource</option>
                    <option *ngFor="let resource of resourceOptions" [value]="resource">
                      {{ resource }}
                    </option>
                  </select>
                </td>
                
                <td>
                  <select formControlName="phaseAndSprint" class="form-control">
                    <option value="">Select</option>
                    <option *ngFor="let phase of phaseOptions" [value]="phase">
                      {{ phase }}
                    </option>
                  </select>
                </td>
                
                <td>
                  <select formControlName="status" class="form-control">
                    <option value="">Select</option>
                    <option *ngFor="let status of statusOptions" [value]="status">
                      {{ status }}
                    </option>
                  </select>
                </td>
                
                <td>
                  <div class="date-range">
                    <input 
                      type="date" 
                      formControlName="taskStartDate"
                      class="form-control date-small">
                    <span>-</span>
                    <input 
                      type="date" 
                      formControlName="taskEndDate"
                      class="form-control date-small">
                  </div>
                </td>
                
                <td>
                  <input 
                    type="text" 
                    formControlName="comments"
                    class="form-control"
                    placeholder="Add comments">
                </td>
                
                <td>
                  <div class="action-buttons">
                    <button 
                      type="button" 
                      class="btn-action btn-add"
                      (click)="addTaskRow()">
                      ⊕
                    </button>
                    <button 
                      type="button" 
                      class="btn-action btn-remove"
                      (click)="removeTaskRow(i)"
                      [disabled]="tasksFormArray.length <= 1">
                      ⊖
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- Submit Button -->
        <div class="submit-section">
          <button 
            type="submit" 
            class="btn btn-primary"
            [disabled]="teamActivityForm.invalid">
            Submit
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

// src/pages/TeamActivity.tsx

import React, { useState } from 'react';
import { Form, Input, Button, Select, DatePicker, Table, Space, Card, Row, Col, message } from 'antd';
import { PlusOutlined, DeleteOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import type { TaskRow, TeamActivityFormData } from '../types';

const { Option } = Select;

const TeamActivity: React.FC = () => {
  const [form] = Form.useForm();
  const [tasks, setTasks] = useState<TaskRow[]>([
    {
      id: 1,
      mainTask: '',
      subTask: '',
      todayTask: '',
      resourceName: '',
      phaseAndSprint: '',
      status: '',
      taskStartDate: dayjs(),
      taskEndDate: dayjs().add(7, 'day'),
      comments: ''
    }
  ]);

  const mainTaskOptions = [
    'Development',
    'Testing',
    'Design',
    'Documentation',
    'Planning'
  ];

  const subTaskOptions = [
    'Frontend Development',
    'Backend Development',
    'API Integration',
    'Unit Testing',
    'Integration Testing',
    'UI Design',
    'UX Research'
  ];

  const resourceOptions = [
    'John Doe',
    'Jane Smith',
    'Mike Johnson',
    'Sarah Wilson',
    'David Brown'
  ];

  const phaseOptions = [
    'Phase 1 - Sprint 1',
    'Phase 1 - Sprint 2',
    'Phase 2 - Sprint 1',
    'Phase 2 - Sprint 2'
  ];

  const statusOptions = [
    'Not Started',
    'In Progress',
    'Completed',
    'Blocked',
    'On Hold'
  ];

  const products = [
    'Product1',
    'Product2',
    'Product3'
  ];

  const addTaskRow = () => {
    const newTask: TaskRow = {
      id: tasks.length + 1,
      mainTask: '',
      subTask: '',
      todayTask: '',
      resourceName: '',
      phaseAndSprint: '',
      status: '',
      taskStartDate: dayjs(),
      taskEndDate: dayjs().add(7, 'day'),
      comments: ''
    };
    setTasks([...tasks, newTask]);
  };

  const removeTaskRow = (id: number) => {
    if (tasks.length > 1) {
      setTasks(tasks.filter(task => task.id !== id));
    }
  };

  const updateTask = (id: number, field: keyof TaskRow, value: any) => {
    setTasks(tasks.map(task => 
      task.id === id ? { ...task, [field]: value } : task
    ));
  };

  const onSubmit = (values: any) => {
    const formData: TeamActivityFormData = {
      ...values,
      tasks: tasks
    };
    console.log('Team Activity Data:', formData);
    message.success('Team activity submitted successfully!');
  };

  const columns = [
    {
      title: 'Main Task',
      dataIndex: 'mainTask',
      key: 'mainTask',
      render: (text: string, record: TaskRow) => (
        <Select
          value={record.mainTask}
          onChange={(value) => updateTask(record.id, 'mainTask', value)}
          style={{ width: '100%' }}
          placeholder="Select main task"
        >
          {mainTaskOptions.map(option => (
            <Option key={option} value={option}>{option}</Option>
          ))}
        </Select>
      )
    },
    {
      title: 'Sub Task',
      dataIndex: 'subTask',
      key: 'subTask',
      render: (text: string, record: TaskRow) => (
        <Select
          value={record.subTask}
          onChange={(value) => updateTask(record.id, 'subTask', value)}
          style={{ width: '100%' }}
          placeholder="Select sub task"
        >
          {subTaskOptions.map(option => (
            <Option key={option} value={option}>{option}</Option>
          ))}
        </Select>
      )
    },
    {
      title: 'Today Task',
      dataIndex: 'todayTask',
      key: 'todayTask',
      render: (text: string, record: TaskRow) => (
        <Input
          value={record.todayTask}
          onChange={(e) => updateTask(record.id, 'todayTask', e.target.value)}
          placeholder="Enter today's task"
        />
      )
    },
    {
      title: 'Resource',
      dataIndex: 'resourceName',
      key: 'resourceName',
      render: (text: string, record: TaskRow) => (
        <Select
          value={record.resourceName}
          onChange={(value) => updateTask(record.id, 'resourceName', value)}
          style={{ width: '100%' }}
          placeholder="Select resource"
        >
          {resourceOptions.map(option => (
            <Option key={option} value={option}>{option}</Option>
          ))}
        </Select>
      )
    },
    {
      title: 'Phase & Sprint',
      dataIndex: 'phaseAndSprint',
      key: 'phaseAndSprint',
      render: (text: string, record: TaskRow) => (
        <Select
          value={record.phaseAndSprint}
          onChange={(value) => updateTask(record.id, 'phaseAndSprint', value)}
          style={{ width: '100%' }}
          placeholder="Select phase"
        >
          {phaseOptions.map(option => (
            <Option key={option} value={option}>{option}</Option>
          ))}
        </Select>
      )
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      render: (text: string, record: TaskRow) => (
        <Select
          value={record.status}
          onChange={(value) => updateTask(record.id, 'status', value)}
          style={{ width: '100%' }}
          placeholder="Select status"
        >
          {statusOptions.map(option => (
            <Option key={option} value={option}>{option}</Option>
          ))}
        </Select>
      )
    },
    {
      title: 'Start Date',
      dataIndex: 'taskStartDate',
      key: 'taskStartDate',
      render: (text: string, record: TaskRow) => (
        <DatePicker
          value={record.taskStartDate}
          onChange={(date) => updateTask(record.id, 'taskStartDate', date)}
          style={{ width: '100%' }}
        />
      )
    },
    {
      title: 'End Date',
      dataIndex: 'taskEndDate',
      key: 'taskEndDate',
      render: (text: string, record: TaskRow) => (
        <DatePicker
          value={record.taskEndDate}
          onChange={(date) => updateTask(record.id, 'taskEndDate', date)}
          style={{ width: '100%' }}
        />
      )
    },
    {
      title: 'Comments',
      dataIndex: 'comments',
      key: 'comments',
      render: (text: string, record: TaskRow) => (
        <Input.TextArea
          value={record.comments}
          onChange={(e) => updateTask(record.id, 'comments', e.target.value)}
          placeholder="Enter comments"
          rows={2}
        />
      )
    },
    {
      title: 'Actions',
      key: 'actions',
      render: (text: string, record: TaskRow) => (
        <Button
          type="text"
          danger
          icon={<DeleteOutlined />}
          onClick={() => removeTaskRow(record.id)}
          disabled={tasks.length === 1}
        />
      )
    }
  ];

  return (
    <div style={{ padding: '24px' }}>
      <Card title="Team Activity" style={{ marginBottom: '24px' }}>
        <Form
          form={form}
          layout="vertical"
          onFinish={onSubmit}
          initialValues={{
            date: dayjs(),
            workingResources: 1,
            selectedProduct: ''
          }}
        >
          <Row gutter={16}>
            <Col xs={24} sm={8}>
              <Form.Item
                label="Date"
                name="date"
                rules={[{ required: true, message: 'Please select date!' }]}
              >
                <DatePicker style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col xs={24} sm={8}>
              <Form.Item
                label="Working Resources"
                name="workingResources"
                rules={[{ required: true, message: 'Please enter working resources!' }]}
              >
                <Input type="number" min={1} />
              </Form.Item>
            </Col>
            <Col xs={24} sm={8}>
              <Form.Item
                label="Selected Product"
                name="selectedProduct"
              >
                <Select placeholder="Select product">
                  {products.map(product => (
                    <Option key={product} value={product}>{product}</Option>
                  ))}
                </Select>
              </Form.Item>
            </Col>
          </Row>
        </Form>
      </Card>

      <Card 
        title="Tasks" 
        extra={
          <Button type="primary" icon={<PlusOutlined />} onClick={addTaskRow}>
            Add Task
          </Button>
        }
      >
        <Table
          columns={columns}
          dataSource={tasks}
          rowKey="id"
          pagination={false}
          scroll={{ x: 1200 }}
        />
        
        <div style={{ marginTop: '24px', textAlign: 'center' }}>
          <Button type="primary" onClick={() => form.submit()}>
            Submit Team Activity
          </Button>
        </div>
      </Card>
    </div>
  );
};

export default TeamActivity;
